namespace SchemaForge.Application.Common.Abstractions;

// Local disk (dev) / MinIO (docker-compose) per Step 1 §9's confirmed decision - never
// Azure/AWS-specific. The caller decides the key (Step 4: SourceDocument.StorageKey is "opaque"
// to IFileStorage itself, not generated by it), so Application controls the naming scheme.
public interface IFileStorage
{
    Task UploadAsync(string key, Stream content, string contentType, CancellationToken cancellationToken);

    Task<Stream> DownloadAsync(string key, CancellationToken cancellationToken);

    Task DeleteAsync(string key, CancellationToken cancellationToken);
}
